# ===============================
# Server Configuration
# ===============================

# Port where the backend will run
server.port=8080

# MongoDB Atlas connection (includes username, password, cluster, and DB name)
spring.data.mongodb.uri=mongodb+srv://samthomas1405:Leo_messi1030@cluster0.2kgb8c0.mongodb.net/voting_data?retryWrites=true&w=majority&appName=Cluster0

# The database name to use (not strictly required if already in the URI, but safe to include)
spring.data.mongodb.database=voting_data


# ===============================
# Application Info
# ===============================

spring.application.name=VotingDataServer
