# MongoDB (Atlas)
spring.data.mongodb.uri=${MONGODB_URI}

# Importer config (used by ChoroplethImporter)
eavs.choro.input=/Users/samuelthomas/projects/416/416-Project/data_clean/results_2024/provisional_choropleth.json
eavs.choro.year=2024
eavs.choro.measure=E1A

# Optional logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.com.pelicans.ingest=INFO

# Your existing app settings are fine to keep:
spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG

